version: '3.7'
services: 
  database:
    container_name: docker-emotionlt-mysql
    image: mysql:5.7.32
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret